// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGXtyyEx945eIKNfMOiUfn33Th_URuv9w',
    appId: '1:52618738218:web:aed3bf34afd9f72458e153',
    messagingSenderId: '52618738218',
    projectId: 'navicode-f8d6b',
    authDomain: 'navicode-f8d6b.firebaseapp.com',
    databaseURL:
        'https://navicode-f8d6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'navicode-f8d6b.appspot.com',
    measurementId: 'G-QZ6WYJD1LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA504yOr4s3unvzO8S_6iSofx13uaQ0jso',
    appId: '1:52618738218:android:80524fdd70041fa858e153',
    messagingSenderId: '52618738218',
    projectId: 'navicode-f8d6b',
    databaseURL:
        'https://navicode-f8d6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'navicode-f8d6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxkcV1jJCww7eq0w_D6XlPjMM4paCPgBM',
    appId: '1:52618738218:ios:7282fe8c25d2887958e153',
    messagingSenderId: '52618738218',
    projectId: 'navicode-f8d6b',
    databaseURL:
        'https://navicode-f8d6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'navicode-f8d6b.appspot.com',
    iosBundleId: 'com.example.navicode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxkcV1jJCww7eq0w_D6XlPjMM4paCPgBM',
    appId: '1:52618738218:ios:7282fe8c25d2887958e153',
    messagingSenderId: '52618738218',
    projectId: 'navicode-f8d6b',
    databaseURL:
        'https://navicode-f8d6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'navicode-f8d6b.appspot.com',
    iosBundleId: 'com.example.navicode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGXtyyEx945eIKNfMOiUfn33Th_URuv9w',
    appId: '1:52618738218:web:fd96ae7aeb82f34058e153',
    messagingSenderId: '52618738218',
    projectId: 'navicode-f8d6b',
    authDomain: 'navicode-f8d6b.firebaseapp.com',
    databaseURL:
        'https://navicode-f8d6b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'navicode-f8d6b.appspot.com',
    measurementId: 'G-TY7TSQ535J',
  );
}
